# Generated by Django 2.2.2 on 2019-06-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190624_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of this category of books', max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
