# Generated by Django 2.2.2 on 2019-06-25 21:43

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category'),
    ]

    operations = [
    ]
