# Generated by Django 2.2.2 on 2019-06-25 21:49

from django.db import migrations


def populate_category(apps, schema_editor):
    Book = apps.get_model('catalog', 'Book')
    Category = apps.get_model('catalog', 'Category')

    c = Category.objects.create(name='Code', slug='Books about code')

    for book in Book.objects.all():
        book.category = c

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190625_2143'),
    ]

    operations = [
        migrations.RunPython(populate_category)
    ]
