# Generated by Django 2.2.2 on 2019-06-26 02:57

from django.db import migrations


def reset_category(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")

    Category.objects.all().delete()

    c = Category.objects.create(name='Code', slug='Books about code')

    for book in Book.objects.all():
        book.category = c


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190625_2149'),
    ]

    operations = [
    ]
