# Generated by Django 2.2.2 on 2019-06-26 03:20

from django.db import migrations

def reset_category(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Book = apps.get_model('catalog', 'Book')


    c = Category.objects.create(name='Code', slug='Books about code')

    for book in Book.objects.all():
        book.category = c

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190626_0319'),
    ]

    operations = [
        migrations.RunPython(reset_category)
    ]
