# Generated by Django 2.2.2 on 2019-06-26 14:28
from datetime import date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190626_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of this category of books', max_length=20)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, help_text="Enter name of book")),
                ('date', models.DateField(default=date.today)),
                ('author', models.CharField(max_length=25, help_text='Enter name of author')),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=144, help_text="enter brief description")),
                ('category', models.ForeignKey('Category', blank=True, null=True, on_delete=models.SET_NULL)),
            ]
        )
    ]
