# Generated by Django 2.2.2 on 2019-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190626_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(help_text='Enter brief description for book', max_length=144),
        ),
    ]
