# Generated by Django 2.2.2 on 2019-06-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20190627_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(help_text='Enter brief description for book', max_length=500),
        ),
    ]
