# Generated by Django 2.2.2 on 2019-06-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20190627_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='catalog.Favorites'),
        ),
    ]
