# Generated by Django 2.2.2 on 2019-06-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190627_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorite',
        ),
        migrations.AddField(
            model_name='favorites',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
        ),
    ]
