# Generated by Django 2.2.2 on 2019-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20190628_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_favorites',
            field=models.IntegerField(default=0),
        ),
    ]
