# Generated by Django 2.2.2 on 2019-06-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_book_num_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='num_favorites',
        ),
    ]
